language: cpp
compiler: gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_script:
  - cd build 
script: 
  - ./facemask_test Users/nishgowda/opencv/opencv/data/haarcascades/haarcascade_frontalface_default.xml /Users/nishgowda/opencv/opencv/data/haarcascades/haarcascade_eye.xml /Users/nishgowda/Desktop/Code/Projects/facemask/data/haarcascade_mcs_mouth.xml /Users/nishgowda/opencv/opencv/data/haarcascades/haarcascade_upperbody.xml

