language: cpp
compiler:
  - gcc
  - clang

sudo: required

dist: trusty

before_script:
  - mkdir built
  - cd built
  - cmake --version
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON ..

script: make && ./facemask_test
