language: cpp
compiler:
  - gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
  
script: 
  - export CC=gcc
  - export CXX=g++
  - cmake --version
  - cmake CMakeLists.txt
  - cmake --build . --target facemask_test

